### ISSUE TITLE
Can this library simply use in MacOSX platform?

### ISSUE THREAD

**Issue by wuseal** [korlibs/klogger#10]
When I add dependency as this:
```kotlin
val macosMain by getting {
            dependencies {
                implementation("com.github.ajalt:clikt-macosx64:2.8.0")
                implementation("com.soywiz.korlibs.klogger:klogger-macosx64:1.10.2")
            }
}
```
after sync, I can only see package without any class in IDEA Panel
![image](https://user-images.githubusercontent.com/9211902/88546101-7d833a00-d04e-11ea-8477-e56ca0398827.png)
Also, I can't find `Logger` class when I coding.
![image](https://user-images.githubusercontent.com/9211902/88546192-9b509f00-d04e-11ea-83b2-a92b1da4c9e3.png)

My Gradle Properties:
```
kotlin.code.style=official
kotlin.import.noCommonSourceSets=true
org.gradle.jvmargs=-Xmx4096M
```
I am using kotlin 1.3.72
Is there anything wrong?

**Comment by soywiz** [comment]
You have to enable metadata in settings.gradle. And also you should probably include klogger instead of klogger-macosx64 I guess

**Comment by soywiz** [comment]
Since there is no reply since last month, let's close this. Feel free to reopen if you still have the problem and can provide more information.
