### ISSUE TITLE
Could not resolve com.soywiz:klogger-jvm:1.6.0.

### ISSUE THREAD

**Issue by benny1611** [korlibs/klogger#7]
Hello,
I've tried to use klogger today, but every time I try to build/resolve dependencies in my project I get an error:
```
* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.soywiz:klogger-jvm:1.6.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/soywiz/klogger-jvm/1.6.0/klogger-jvm-1.6.0.pom
       - https://repo.maven.apache.org/maven2/com/soywiz/klogger-jvm/1.6.0/klogger-jvm-1.6.0.jar
       - https://jcenter.bintray.com/com/soywiz/klogger-jvm/1.6.0/klogger-jvm-1.6.0.pom
       - https://jcenter.bintray.com/com/soywiz/klogger-jvm/1.6.0/klogger-jvm-1.6.0.jar
       - https://dl.bintray.com/korlibs/korlibs/com/soywiz/klogger-jvm/1.6.0/klogger-jvm-1.6.0.pom
       - https://dl.bintray.com/korlibs/korlibs/com/soywiz/klogger-jvm/1.6.0/klogger-jvm-1.6.0.jar
     Required by:
         project :
```

I've tried to access those URLs with my web browser, but then I've got an 404. Can you please tell me what I'm doing wrong or point me in the right direction? Thank you!

Cheers,
Benny

**Comment by soywiz** [comment]
Where did you found that artifact location? Looks wrong, maybe something is outdated.

This is the right location:
https://dl.bintray.com/korlibs/korlibs/com/soywiz/korlibs/klogger/klogger-jvm/1.10.1/

```
com.soywiz.korlibs.klogger:klogger-jvm:1.10.1
```

**Comment by benny1611** [comment]
I've found it here: https://bintray.com/korlibs/korlibs/klogger

It's in the README.md in the master branch of this project. Thank you for the fast reply! 😄
